package com.scgexpress.backoffice.android.model

import com.google.gson.annotations.SerializedName
import java.io.Serializable

data class TrackingInfo(
        @SerializedName("id") val id: String = "",
        @SerializedName("tracking_number") var trackingNumber: String = "",
        @SerializedName("running_number") val runningNumber: String = "",
        @SerializedName("consignment_id") val consignmentID: String = "",
        @SerializedName("id_referred_parcel") val idReferredParcel: String = "",
        @SerializedName("id_parcel_properties") val idParcelProperties: String = "",
        @SerializedName("id_parcel_sizing") val idParcelSizing: String = "",
        @SerializedName("id_service_type_level_1") val idServiceTypeLevel1: String = "",
        @SerializedName("id_service_type_level_2") val idServiceTypeLevel2: String = "",
        @SerializedName("id_service_type_level_3") val idServiceTypeLevel3: String = "",
        @SerializedName("parcel_status") val parcelStatus: String = "",
        @SerializedName("parcel_description") val parcelDescription: String = "",
        @SerializedName("id_status") val idStatus: String = "",
        @SerializedName("sender_code") val senderCode: String = "",
        @SerializedName("sender_name") val senderName: String = "",
        @SerializedName("sender_tel") val senderTel: String = "",
        @SerializedName("sender_address") val senderAddress: String = "",
        @SerializedName("sender_zipcode") val senderZipcode: String = "",
        @SerializedName("sender_province") val senderProvince: String = "",
        @SerializedName("sender_district") val senderDistrict: String = "",
        @SerializedName("recipient_code") val recipientCode: String = "",
        @SerializedName("recipient_name") val recipientName: String = "",
        @SerializedName("recipient_tel") val recipientTel: String = "",
        @SerializedName("recipient_contact_name") val recipientContactName: String = "",
        @SerializedName("recipient_contact_tel") val recipientContactTel: String = "",
        @SerializedName("recipient_address") val recipientAddress: String = "",
        @SerializedName("recipient_zipcode") val recipientZipcode: String = "",
        @SerializedName("recipient_province") val recipientProvince: String = "",
        @SerializedName("recipient_district") val recipientDistrict: String = "",
        @SerializedName("parcel_weight_kg") val parcelWeightKg: String = "",
        @SerializedName("parcel_size") val parcelSize: String = "",
        @SerializedName("cod_amount") val codAmount: String = "",
        @SerializedName("cod_fee_amount") val codFeeAmount: String = "",
        @SerializedName("user_note") val userNote: String = "",
        @SerializedName("neko_status_code") val nekoStatusCode: String = "",
        @SerializedName("neko_status_name") val nekoStatusName: String = "",
        @SerializedName("date_created") val dateCreated: String = "",
        @SerializedName("date_modified") val dateModified: String = "",
        @SerializedName("date_delivered") val dateDelivered: String = "",
        @SerializedName("recipient_image") val recipientImage: List<String> = listOf(),
        @SerializedName("recipient_parcel_image") val recipientParcelImage: String = "",
        @SerializedName("signature_image") val signatureImage: String = "",
        @SerializedName("recipient_sign_name") val recipientSignName: String = "",
        @SerializedName("ofd_notes") val ofdNotes: String = ""
) : Serializable