package com.scgexpress.backoffice.android.db.entity.masterdata

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Ignore
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName
import com.squareup.moshi.Json

@Entity(tableName = "tbl_scg_parcels")
data class TblScgParcels(
    @PrimaryKey @Json(name = "id") @SerializedName("id") @ColumnInfo(name = "id") var id: Int = 0,
    @Json(name = "tracking_number") @SerializedName("tracking_number") @ColumnInfo(name = "tracking_number") var trackingNumber: String? = "",
    @Json(name = "running_number") @SerializedName("running_number") @ColumnInfo(name = "running_number") var runningNumber: Int = 0,
    @Json(name = "consignment_id") @SerializedName("consignment_id") @ColumnInfo(name = "consignment_id") var consignmentId: Int = 0,
    @Json(name = "id_referred_parcel") @SerializedName("id_referred_parcel") @ColumnInfo(name = "id_referred_parcel") var idReferredParcel: Int = 0,
    @Json(name = "parcel_status") @SerializedName("parcel_status") @ColumnInfo(name = "parcel_status") var parcelStatus: Int = 61,
    @Json(name = "parcel_description") @SerializedName("parcel_description") @ColumnInfo(name = "parcel_description") var parcelDescription: String? = "",
    @Json(name = "parcel_note") @SerializedName("parcel_note") @ColumnInfo(name = "parcel_note") var parcelNote: String? = "",
    @Json(name = "job_type") @SerializedName("job_type") @ColumnInfo(name = "job_type") var jobType: Int = 60,
    @Json(name = "service_require") @SerializedName("service_require") @ColumnInfo(name = "service_require") var serviceRequire: Int = 57,
    @Json(name = "user_id") @SerializedName("user_id") @ColumnInfo(name = "user_id") var userId: Int = 0,
    @Json(name = "user_order_date") @SerializedName("user_order_date") @ColumnInfo(name = "user_order_date") var userOrderDate: String? = "",
    @Json(name = "user_commit_date") @SerializedName("user_commit_date") @ColumnInfo(name = "user_commit_date") var userCommitDate: String? = "",
    @Json(name = "user_description") @SerializedName("user_description") @ColumnInfo(name = "user_description") var userDescription: String? = "",
    @Json(name = "user_note") @SerializedName("user_note") @ColumnInfo(name = "user_note") var userNote: String? = "",
    @Json(name = "member_code") @SerializedName("member_code") @ColumnInfo(name = "member_code") var memberCode: String? = "",
    @Json(name = "sender_code") @SerializedName("sender_code") @ColumnInfo(name = "sender_code") var senderCode: String? = "",
    @Json(name = "sender_name") @SerializedName("sender_name") @ColumnInfo(name = "sender_name") var senderName: String? = "",
    @Json(name = "sender_tel") @SerializedName("sender_tel") @ColumnInfo(name = "sender_tel") var senderTel: String? = "",
    @Json(name = "sender_address") @SerializedName("sender_address") @ColumnInfo(name = "sender_address") var senderAddress: String? = "",
    @Json(name = "sender_zipcode") @SerializedName("sender_zipcode") @ColumnInfo(name = "sender_zipcode") var senderZipcode: String? = "",
    @Json(name = "recipient_code") @SerializedName("recipient_code") @ColumnInfo(name = "recipient_code") var recipientCode: String? = "",
    @Json(name = "recipient_name") @SerializedName("recipient_name") @ColumnInfo(name = "recipient_name") var recipientName: String? = "",
    @Json(name = "recipient_tel") @SerializedName("recipient_tel") @ColumnInfo(name = "recipient_tel") var recipientTel: String? = "",
    @Json(name = "recipient_contact_name") @SerializedName("recipient_contact_name") @ColumnInfo(name = "recipient_contact_name") var recipientContactName: String? = "",
    @Json(name = "recipient_contact_tel") @SerializedName("recipient_contact_tel") @ColumnInfo(name = "recipient_contact_tel") var recipientContactTel: String? = "",
    @Json(name = "recipient_address") @SerializedName("recipient_address") @ColumnInfo(name = "recipient_address") var recipientAddress: String? = "",
    @Json(name = "recipient_zipcode") @SerializedName("recipient_zipcode") @ColumnInfo(name = "recipient_zipcode") var recipientZipcode: String? = "",
    @Json(name = "parcel_weight_kg") @SerializedName("parcel_weight_kg") @ColumnInfo(name = "parcel_weight_kg") var parcelWeightKg: String? = "",
    @Json(name = "parcel_size") @SerializedName("parcel_size") @ColumnInfo(name = "parcel_size") var parcelSize: Int = 82,
    @Json(name = "parcel_cool_type") @SerializedName("parcel_cool_type") @ColumnInfo(name = "parcel_cool_type") var parcelCoolType: Int = 86,
    @Json(name = "parcel_delivery_charge") @SerializedName("parcel_delivery_charge") @ColumnInfo(name = "parcel_delivery_charge") var parcelDeliveryCharge: String? = "",
    @Json(name = "parcel_surcharge") @SerializedName("parcel_surcharge") @ColumnInfo(name = "parcel_surcharge") var parcelSurcharge: String? = "",
    @Json(name = "cod_amount") @SerializedName("cod_amount") @ColumnInfo(name = "cod_amount") var codAmount: String? = "",
    @Json(name = "cod_fee_amount") @SerializedName("cod_fee_amount") @ColumnInfo(name = "cod_fee_amount") var codFeeAmount: String? = "",
    @Json(name = "cod_fee_issued_date") @SerializedName("cod_fee_issued_date") @ColumnInfo(name = "cod_fee_issued_date") var codFeeIssuedDate: String? = "",
    @Json(name = "cbm_amount") @SerializedName("cbm_amount") @ColumnInfo(name = "cbm_amount") var cbmAmount: String? = "",
    @Json(name = "cbm_issued_date") @SerializedName("cbm_issued_date") @ColumnInfo(name = "cbm_issued_date") var cbmIssuedDate: String? = "",
    @Json(name = "date_created") @SerializedName("date_created") @ColumnInfo(name = "date_created") var dateCreated: String? = "",
    @Json(name = "date_committed") @SerializedName("date_committed") @ColumnInfo(name = "date_committed") var dateCommitted: String? = "",
    @Json(name = "date_delivered") @SerializedName("date_delivered") @ColumnInfo(name = "date_delivered") var dateDelivered: String? = "",
    @Json(name = "date_modified") @SerializedName("date_modified") @ColumnInfo(name = "date_modified") var dateModified: String? = "",
    @Json(name = "date_pickup") @SerializedName("date_pickup") @ColumnInfo(name = "date_pickup") var datePickup: String? = "",
    @Json(name = "neko_pickup_branch_code") @SerializedName("neko_pickup_branch_code") @ColumnInfo(name = "neko_pickup_branch_code") var nekoPickupBranchCode: String? = "",
    @Json(name = "neko_status_code") @SerializedName("neko_status_code") @ColumnInfo(name = "neko_status_code") var nekoStatusCode: String? = "E2",
    @Json(name = "neko_status_name") @SerializedName("neko_status_name") @ColumnInfo(name = "neko_status_name") var nekoStatusName: String? = "ไม่ได้ลงทะเบียน",
    @Json(name = "neko_arrive_branch_name") @SerializedName("neko_arrive_branch_name") @ColumnInfo(name = "neko_arrive_branch_name") var nekoArriveBranchName: String? = "",
    @Json(name = "neko_size_code") @SerializedName("neko_size_code") @ColumnInfo(name = "neko_size_code") var nekoSizeCode: String? = "",
    @Json(name = "neko_input_datetime") @SerializedName("neko_input_datetime") @ColumnInfo(name = "neko_input_datetime") var nekoInputDatetime: String? = "",
    @Json(name = "neko_date_updated") @SerializedName("neko_date_updated") @ColumnInfo(name = "neko_date_updated") var nekoDateUpdated: String? = "",
    @Json(name = "push_status") @SerializedName("push_status") @ColumnInfo(name = "push_status") var pushStatus: String? = "N",
    @Json(name = "recipient_signed") @SerializedName("recipient_signed") @ColumnInfo(name = "recipient_signed") var recipientSigned: String? = "",
    @Json(name = "status_migrate_to_c2v2") @SerializedName("status_migrate_to_c2v2") @ColumnInfo(name = "status_migrate_to_c2v2") var statusMigrateToC2v2: String? = "N",
    @Json(name = "id_parcel_properties") @SerializedName("id_parcel_properties") @ColumnInfo(name = "id_parcel_properties") var idParcelProperties: Int = 1,
    @Json(name = "id_parcel_sizing") @SerializedName("id_parcel_sizing") @ColumnInfo(name = "id_parcel_sizing") var idParcelSizing: Int = 1,
    @Json(name = "id_service_type_level_1") @SerializedName("id_service_type_level_1") @ColumnInfo(name = "id_service_type_level_1") var idServiceTypeLevel1: Int = 1,
    @Json(name = "id_service_type_level_2") @SerializedName("id_service_type_level_2") @ColumnInfo(name = "id_service_type_level_2") var idServiceTypeLevel2: Int = 1,
    @Json(name = "id_service_type_level_3") @SerializedName("id_service_type_level_3") @ColumnInfo(name = "id_service_type_level_3") var idServiceTypeLevel3: Int = 1,
    @Json(name = "status_temperature_control") @SerializedName("status_temperature_control") @ColumnInfo(name = "status_temperature_control") var statusTemperatureControl: String? = "N",
    @Json(name = "id_temperature_control_type") @SerializedName("id_temperature_control_type") @ColumnInfo(name = "id_temperature_control_type") var idTemperatureControlType: Int = 1,
    @Json(name = "c2_freight_fare") @SerializedName("c2_freight_fare") @ColumnInfo(name = "c2_freight_fare") var c2FreightFare: String? = "",
    @Json(name = "id_users_print_waybill") @SerializedName("id_users_print_waybill") @ColumnInfo(name = "id_users_print_waybill") var idUsersPrintWaybill: Int = 0,
    @Json(name = "datetime_print_waybill") @SerializedName("datetime_print_waybill") @ColumnInfo(name = "datetime_print_waybill") var datetimePrintWaybill: String? = "",
    @Json(name = "datetime_print_waybill_index") @SerializedName("datetime_print_waybill_index") @ColumnInfo(name = "datetime_print_waybill_index") var datetimePrintWaybillIndex: String? = "",
    @Json(name = "sender_province") @SerializedName("sender_province") @ColumnInfo(name = "sender_province") var senderProvince: String? = "",
    @Json(name = "sender_district") @SerializedName("sender_district") @ColumnInfo(name = "sender_district") var senderDistrict: String? = "",
    @Json(name = "recipient_province") @SerializedName("recipient_province") @ColumnInfo(name = "recipient_province") var recipientProvince: String? = "",
    @Json(name = "recipient_district") @SerializedName("recipient_district") @ColumnInfo(name = "recipient_district") var recipientDistrict: String? = "",
    @Json(name = "total_price") @SerializedName("total_price") @ColumnInfo(name = "total_price") var totalPrice: String? = "",
    @Json(name = "order_queue") @SerializedName("order_queue") @ColumnInfo(name = "order_queue") var orderQueue: Int = 0,
    @Json(name = "product_value") @SerializedName("product_value") @ColumnInfo(name = "product_value") var productValue: String? = "",
    @Json(name = "status_delete") @SerializedName("status_delete") @ColumnInfo(name = "status_delete") var statusDelete: String? = "N",
    @Json(name = "modify_user_id") @SerializedName("modify_user_id") @ColumnInfo(name = "modify_user_id") var modifyUserId: Int = 0,
    @Json(name = "c2_promo_discount") @SerializedName("c2_promo_discount") @ColumnInfo(name = "c2_promo_discount") var c2PromoDiscount: String? = "",
    @Json(name = "c2_net_fright_fare") @SerializedName("c2_net_fright_fare") @ColumnInfo(name = "c2_net_fright_fare") var c2NetFrightFare: String? = "",
    @Json(name = "id_promo") @SerializedName("id_promo") @ColumnInfo(name = "id_promo") var idPromo: Int = 0
) {
    @Ignore
    constructor() : this(0)
}